sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t timparx/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true timparx/react-test npm test

after_success:
  - docker build -t timparx/multi-client ./client
  - docker build -t timparx/multi-nginx ./nginx
  - docker build -t timparx/multi-server ./server
  - docker build -t timparx/multi-worker ./worker

  # Tag images explicitly with :latest
  - docker tag timparx/multi-client docker.io/timparx/multi-client:latest
  - docker tag timparx/multi-nginx docker.io/timparx/multi-nginx:latest
  - docker tag timparx/multi-server docker.io/timparx/multi-server:latest
  - docker tag timparx/multi-worker docker.io/timparx/multi-worker:latest

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take those images and push them to docker hub 
  - docker push docker.io/timparx/multi-client:latest
  - docker push docker.io/timparx/multi-nginx:latest
  - docker push docker.io/timparx/multi-server:latest
  - docker push docker.io/timparx/multi-worker:latest

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-north-1-302001396912
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
